version: "2.4"
services:
  sonarqube:
    image: sonarqube
    expose:
        - "9000"
    ports:
        - "9000:9000"
    volumes:
        - ./sonarqube_data:/opt/sonarqube/data:rw
        - ./sonarqube_extensions:/opt/sonarqube/extensions:rw
        - ./sonarqube_logs:/opt/sonarqube/logs:rw
    environment:
        SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/postgres
        SONAR_JDBC_USERNAME: postgres
        SONAR_JDBC_PASSWORD: Admin@1357
  postgres:
    image: postgres
    expose:
        - "5432"
    volumes:
        - ./postgres_data:/var/lib/postgresql/data:rw
    environment:
        POSTGRES_PASSWORD: Admin@1357
        PGDATA: /var/lib/postgresql/data/pgdata
  nexus3-repo:
    image: sonatype/nexus3
    expose:
        - "8081"
    ports:
        - "8081:8081"
    volumes:
        - ./nexus_data:/nexus-data:rw
