apiVersion: "v1"
kind: "Service"
metadata:
  name: "jenkins-deployment-service"
  namespace: "namespace-value"
  labels:
    app.kubernetes.io/managed-by: "graphite-jenkins-gke"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "jenkins-deployment"
  type: "LoadBalancer"
  loadBalancerIP: ""
